2014-08-21 10:36:07 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /app/
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AppController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 10:54:16 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:54:16 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:56:16 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:56:16 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:56:29 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:56:29 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:56:30 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:56:30 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:56:30 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:56:30 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:58:41 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:58:41 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:58:42 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:58:42 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:58:42 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:58:42 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:58:42 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:58:42 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 10:58:42 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 10:58:42 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:00:25 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:00:25 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:00:36 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:00:36 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:01:46 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 8]
2014-08-21 11:01:46 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 8, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 8, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:01:47 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 8]
2014-08-21 11:01:47 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 8, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 8, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:01:48 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 8]
2014-08-21 11:01:48 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 8, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 8, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:01:48 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 8]
2014-08-21 11:01:48 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 8, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 8, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:01:50 Error: Fatal Error (4): syntax error, unexpected '$video' (T_VARIABLE) in [E:\te\tests\2\app\Controller\IndexController.php, line 8]
2014-08-21 11:01:50 Error: [FatalErrorException] syntax error, unexpected '$video' (T_VARIABLE)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\te\tests\2\a...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\te\tests\2\a...', 8, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\te\tests\2\a...', 8, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:03:11 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:03:11 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:03:11 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:03:11 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:03:12 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:03:12 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:03:12 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:03:12 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:03:14 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:03:14 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:03:51 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:03:51 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:03:51 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:03:51 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:04:50 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:04:50 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:04:51 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:04:51 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:04:51 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:04:51 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:04:51 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:04:51 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:04:52 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:04:52 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:04:52 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:04:52 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:04:52 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:04:52 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:19 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:19 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:19 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:19 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:53 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:53 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:58 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:58 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:58 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:58 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:58 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:58 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:58 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:58 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:59 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:59 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:05:59 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:05:59 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:06:15 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:06:15 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:06:19 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:06:19 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:06:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:06:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:06:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:06:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:06:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:06:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:07:05 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:07:05 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:07:06 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:07:06 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:07:06 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 7]
2014-08-21 11:07:06 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 7, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:08:19 Error: [MissingTableException] Table videos for model video was not found in datasource default.
Exception Attributes: array (
  'table' => 'videos',
  'class' => 'video',
  'ds' => 'default',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Model\Model.php(3525): Model->setSource('videos')
#1 E:\te\tests\2\lib\Cake\Model\Model.php(2921): Model->getDataSource()
#2 E:\te\tests\2\lib\Cake\Model\Model.php(2893): Model->_readDataSource('all', Array)
#3 E:\te\tests\2\app\Controller\IndexController.php(9): Model->find('all')
#4 [internal function]: IndexController->index('home')
#5 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#6 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#7 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#8 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-08-21 11:08:33 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:09:25 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:09:32 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:09:46 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:09:55 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:09:57 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:09:57 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:09:58 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:09:58 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:10:19 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:10:43 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:11:19 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 9]
2014-08-21 11:11:19 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 9, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 9, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:11:46 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\IndexController.php, line 9]
2014-08-21 11:11:46 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 9, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 9, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:11:50 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:12:00 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:12:00 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:12:09 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:13:13 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:14:51 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:15:03 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:15:14 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:15:20 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\index.ctp',
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:18:32 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(15): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:11 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(15): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:12 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(15): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:22 Error: [MissingModelException] Videos
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Videos', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(15): Controller->paginate('Videos')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:23 Error: [MissingModelException] Videos
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Videos', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(15): Controller->paginate('Videos')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:31 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(15): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:47 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(12): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:48 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(12): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:48 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(12): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:48 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(12): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:19:48 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(12): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:24:47 Error: [MissingModelException] Video
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Video', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(15): Controller->paginate('Video')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:24:54 Error: [MissingModelException] Videos
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Videos', Array, Array)
#1 E:\te\tests\2\app\Controller\IndexController.php(15): Controller->paginate('Videos')
#2 [internal function]: IndexController->index('home')
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:28:13 Error: Fatal Error (1): Call to a member function prev() on a non-object in [E:\te\tests\2\app\View\Video\index.ctp, line 11]
2014-08-21 11:28:13 Error: [FatalErrorException] Call to a member function prev() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 11, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 11, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:30:47 Error: Fatal Error (1): Call to a member function numbers() on a non-object in [E:\te\tests\2\app\View\Video\index.ctp, line 11]
2014-08-21 11:30:47 Error: [FatalErrorException] Call to a member function numbers() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 11, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 11, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:31:12 Error: Fatal Error (1): Call to a member function numbers() on a non-object in [E:\te\tests\2\app\View\Video\index.ctp, line 11]
2014-08-21 11:31:12 Error: [FatalErrorException] Call to a member function numbers() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 11, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 11, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:38:11 Error: [MissingHelperException] Helper class PaginationHelper could not be found.
Exception Attributes: array (
  'class' => 'PaginationHelper',
  'plugin' => false,
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(886): HelperCollection->load('Pagination', Array)
#1 E:\te\tests\2\lib\Cake\View\View.php(354): View->loadHelpers()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(1241): View->__construct(Object(IndexController))
#3 E:\te\tests\2\lib\Cake\Controller\Controller.php(940): Controller->_getViewObject()
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#5 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#6 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-08-21 11:40:49 Error: Fatal Error (1): Call to a member function numbers() on a non-object in [E:\te\tests\2\app\View\Video\index.ctp, line 12]
2014-08-21 11:40:49 Error: [FatalErrorException] Call to a member function numbers() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 12, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 12, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:43:14 Error: Fatal Error (1): Call to a member function numbers() on a non-object in [E:\te\tests\2\app\View\Video\index.ctp, line 12]
2014-08-21 11:43:14 Error: [FatalErrorException] Call to a member function numbers() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 12, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 12, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:44:01 Error: Fatal Error (1): Call to a member function numbers() on a non-object in [E:\te\tests\2\app\View\Video\index.ctp, line 12]
2014-08-21 11:44:01 Error: [FatalErrorException] Call to a member function numbers() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 12, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 12, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:44:01 Error: Fatal Error (1): Call to a member function numbers() on a non-object in [E:\te\tests\2\app\View\Video\index.ctp, line 12]
2014-08-21 11:44:01 Error: [FatalErrorException] Call to a member function numbers() on a non-object
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 12, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 12, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 11:51:39 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\add.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\add.ctp',
)
Request URL: /video/add
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 11:51:58 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\add.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\add.ctp',
)
Request URL: /video/add
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 12:01:24 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\te\tests\2\app\View\Video\add.ctp, line 2]
2014-08-21 12:01:24 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /video/add
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 2)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 2, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 2, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 12:02:34 Error: [MissingComponentException] Component class FormComponent could not be found.
Exception Attributes: array (
  'class' => 'FormComponent',
  'plugin' => false,
)
Request URL: /video/add
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Form', Array)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(IndexController))
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(186): Controller->constructClasses()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 12:03:30 Error: Fatal Error (1): Call to a member function create() on a non-object in [E:\te\tests\2\app\View\Video\add.ctp, line 2]
2014-08-21 12:03:30 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /video/add
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 2)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 2, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 2, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 12:29:04 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND 1    LIMIT 5' at line 1
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `video`....', Array)
#2 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `video`....', Array, Array)
#3 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `video`....', false)
#4 E:\te\tests\2\lib\Cake\Model\Model.php(2921): DboSource->read(Object(Video), Array)
#5 E:\te\tests\2\lib\Cake\Model\Model.php(2893): Model->_readDataSource('all', Array)
#6 E:\te\tests\2\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\te\tests\2\app\Controller\IndexController.php(18): PaginatorComponent->paginate('video')
#8 [internal function]: IndexController->index('home')
#9 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(IndexController), Array)
#10 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#12 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-08-21 12:33:42 Error: [MissingControllerException] Controller class AsdasdController could not be found.
Exception Attributes: array (
  'class' => 'AsdasdController',
  'plugin' => NULL,
)
Request URL: /asdasd
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 13:03:07 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 13:04:13 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 13:04:18 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 13:07:25 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 13:09:04 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 13:09:05 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 13:09:09 Error: [MissingActionException] Action AdminController::login() could not be found.
Exception Attributes: array (
  'controller' => 'AdminController',
  'action' => 'login',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AdminController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 13:09:43 Error: [MissingViewException] View file "E:\te\tests\2\app\View\Admin\auth.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\Admin\\auth.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AdminController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 13:31:05 Error: [MissingViewException] View file "E:\te\tests\2\app\View\Admin\auth.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\Admin\\auth.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AdminController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 13:56:36 Error: [MissingActionException] Action AdminController::auth() could not be found.
Exception Attributes: array (
  'controller' => 'AdminController',
  'action' => 'auth',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AdminController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 13:56:53 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 13:57:31 Error: [MissingActionException] Action UsersController::users() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'users',
)
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 13:58:01 Error: [MissingViewException] View file "E:\te\tests\2\app\View\Users\users.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\Users\\users.ctp',
)
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 13:58:34 Error: [MissingViewException] View file "E:\te\tests\2\app\View\Users\users.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\Users\\users.ctp',
)
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 14:06:44 Error: [MissingViewException] View file "E:\te\tests\2\app\View\User\users.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\User\\users.ctp',
)
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 14:10:21 Error: Fatal Error (64): Cannot redeclare class Users in [E:\te\tests\2\app\Model\User.php, line 28]
2014-08-21 14:10:21 Error: [FatalErrorException] Cannot redeclare class Users
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 14:10:29 Error: Fatal Error (64): Cannot redeclare class Users in [E:\te\tests\2\app\Model\User.php, line 28]
2014-08-21 14:10:29 Error: [FatalErrorException] Cannot redeclare class Users
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 14:16:56 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 14:17:14 Error: [MissingActionException] Action UserController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UserController',
  'action' => 'login',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 14:17:29 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 14:17:40 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 14:17:45 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /users/users/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 14:18:02 Error: [MissingActionException] Action UserController::user() could not be found.
Exception Attributes: array (
  'controller' => 'UserController',
  'action' => 'user',
)
Request URL: /user/user/login
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 14:18:16 Error: [MissingActionException] Action UserController::user() could not be found.
Exception Attributes: array (
  'controller' => 'UserController',
  'action' => 'user',
)
Request URL: /user/user/login
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 14:18:22 Error: [MissingControllerException] Controller class LoginController could not be found.
Exception Attributes: array (
  'class' => 'LoginController',
  'plugin' => NULL,
)
Request URL: /login/user/login
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 14:18:35 Error: [MissingViewException] View file "E:\te\tests\2\app\View\User\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\User\\login.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 14:18:48 Error: [MissingViewException] View file "E:\te\tests\2\app\View\User\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\User\\login.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 14:18:51 Error: [MissingViewException] View file "E:\te\tests\2\app\View\User\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\User\\login.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 14:18:51 Error: [MissingViewException] View file "E:\te\tests\2\app\View\User\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\User\\login.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 14:18:51 Error: [MissingViewException] View file "E:\te\tests\2\app\View\User\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\User\\login.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 14:18:52 Error: [MissingViewException] View file "E:\te\tests\2\app\View\User\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\User\\login.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 14:19:04 Error: Fatal Error (64): Cannot redeclare class Users in [E:\te\tests\2\app\Model\User.php, line 28]
2014-08-21 14:19:04 Error: [FatalErrorException] Cannot redeclare class Users
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 28, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 14:35:24 Error: Fatal Error (1): Class 'AuthComponent' not found in [E:\te\tests\2\lib\Cake\Routing\Dispatcher.php, line 241]
2014-08-21 14:35:24 Error: [FatalErrorException] Class 'AuthComponent' not found
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'AuthComp...', 'E:\te\tests\2\l...', 241)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'AuthComp...', 'E:\te\tests\2\l...', 241, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'AuthComp...', 'E:\te\tests\2\l...', 241, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 14:42:24 Error: [UnauthorizedException] Unauthorized
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(348): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(304): AuthComponent->_unauthenticated(Object(UserController))
#2 [internal function]: AuthComponent->startup(Object(UserController))
#3 E:\te\tests\2\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 E:\te\tests\2\lib\Cake\Event\CakeEventManager.php(242): call_user_func(Array, Object(CakeEvent))
#6 E:\te\tests\2\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(187): Controller->startupProcess()
#8 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#9 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-08-21 14:42:34 Error: [UnauthorizedException] Unauthorized
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(348): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(304): AuthComponent->_unauthenticated(Object(UserController))
#2 [internal function]: AuthComponent->startup(Object(UserController))
#3 E:\te\tests\2\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 E:\te\tests\2\lib\Cake\Event\CakeEventManager.php(242): call_user_func(Array, Object(CakeEvent))
#6 E:\te\tests\2\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(187): Controller->startupProcess()
#8 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#9 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-08-21 14:42:37 Error: [UnauthorizedException] Unauthorized
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(348): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(304): AuthComponent->_unauthenticated(Object(UserController))
#2 [internal function]: AuthComponent->startup(Object(UserController))
#3 E:\te\tests\2\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 E:\te\tests\2\lib\Cake\Event\CakeEventManager.php(242): call_user_func(Array, Object(CakeEvent))
#6 E:\te\tests\2\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(187): Controller->startupProcess()
#8 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#9 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-08-21 14:42:45 Error: [UnauthorizedException] Unauthorized
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(348): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(304): AuthComponent->_unauthenticated(Object(UserController))
#2 [internal function]: AuthComponent->startup(Object(UserController))
#3 E:\te\tests\2\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 E:\te\tests\2\lib\Cake\Event\CakeEventManager.php(242): call_user_func(Array, Object(CakeEvent))
#6 E:\te\tests\2\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(187): Controller->startupProcess()
#8 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#9 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-08-21 14:43:07 Error: [MissingPluginException] Plugin Users could not be found.
Exception Attributes: array (
  'plugin' => 'Users',
)
Request URL: /admin/auth
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Core\App.php(227): CakePlugin::path('Users')
#1 E:\te\tests\2\lib\Cake\Core\App.php(549): App::path('Model', 'Users')
#2 [internal function]: App::load('User')
#3 [internal function]: spl_autoload_call('User')
#4 E:\te\tests\2\lib\Cake\Utility\ClassRegistry.php(146): class_exists('User')
#5 E:\te\tests\2\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(108): ClassRegistry::init('Users.User')
#6 E:\te\tests\2\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(79): BaseAuthenticate->_findUser('123', '123')
#7 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(752): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#8 E:\te\tests\2\lib\Cake\Controller\Component\AuthComponent.php(599): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#9 E:\te\tests\2\app\Controller\UserController.php(27): AuthComponent->login()
#10 [internal function]: UserController->login()
#11 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#12 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#13 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#14 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-08-21 15:36:57 Error: [MissingActionException] Action UserController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'UserController',
  'action' => 'edit',
)
Request URL: /user/edit
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 15:37:52 Error: [MissingActionException] Action UserController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'UserController',
  'action' => 'edit',
)
Request URL: /admin/edit
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 15:55:12 Error: [MissingControllerException] Controller class AdminController could not be found.
Exception Attributes: array (
  'class' => 'AdminController',
  'plugin' => NULL,
)
Request URL: /admin/edit
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 15:55:22 Error: [MissingActionException] Action UserController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'UserController',
  'action' => 'edit',
)
Request URL: /user/edit
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 15:55:54 Error: [MissingActionException] Action UserController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'UserController',
  'action' => 'edit',
)
Request URL: /user/edit
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#2 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-21 15:56:16 Error: [MissingViewException] View file "E:\te\tests\2\app\View\User\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\User\\view.ctp',
)
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 16:00:14 Error: Fatal Error (64): Cannot redeclare UserController::$components in [E:\te\tests\2\app\Controller\UserController.php, line 30]
2014-08-21 16:00:14 Error: [FatalErrorException] Cannot redeclare UserController::$components
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 30)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 30, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'E:\te\tests\2\a...', 30, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:00:40 Error: [MissingModelException] Video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(53): PaginatorComponent->paginate('Video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:01:57 Error: [MissingModelException] Videos
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(53): PaginatorComponent->paginate('Videos')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:02:00 Error: [MissingModelException] Video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(53): PaginatorComponent->paginate('Video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:02:09 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Video.active' in 'where clause'
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `User`.`...', false)
#4 E:\te\tests\2\lib\Cake\Model\Model.php(2921): DboSource->read(Object(User), Array)
#5 E:\te\tests\2\lib\Cake\Model\Model.php(2893): Model->_readDataSource('all', Array)
#6 E:\te\tests\2\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\te\tests\2\app\Controller\UserController.php(53): PaginatorComponent->paginate('User')
#8 [internal function]: UserController->view()
#9 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#10 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#12 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-08-21 16:02:45 Error: Fatal Error (1): Class 'Video' not found in [E:\te\tests\2\app\Controller\UserController.php, line 53]
2014-08-21 16:02:45 Error: [FatalErrorException] Class 'Video' not found
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'Video' n...', 'E:\te\tests\2\a...', 53)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Video' n...', 'E:\te\tests\2\a...', 53, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'Video' n...', 'E:\te\tests\2\a...', 53, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:03:21 Error: Fatal Error (1): Class 'Video' not found in [E:\te\tests\2\app\Controller\UserController.php, line 54]
2014-08-21 16:03:21 Error: [FatalErrorException] Class 'Video' not found
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'Video' n...', 'E:\te\tests\2\a...', 54)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Video' n...', 'E:\te\tests\2\a...', 54, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'Video' n...', 'E:\te\tests\2\a...', 54, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:03:29 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Video.active' in 'where clause'
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `User`.`...', false)
#4 E:\te\tests\2\lib\Cake\Model\Model.php(2921): DboSource->read(Object(User), Array)
#5 E:\te\tests\2\lib\Cake\Model\Model.php(2893): Model->_readDataSource('all', Array)
#6 E:\te\tests\2\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\te\tests\2\app\Controller\UserController.php(55): PaginatorComponent->paginate(NULL)
#8 [internal function]: UserController->view()
#9 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#10 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#12 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-08-21 16:03:51 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Video.active' in 'where clause'
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `User`.`...', false)
#4 E:\te\tests\2\lib\Cake\Model\Model.php(2921): DboSource->read(Object(User), Array)
#5 E:\te\tests\2\lib\Cake\Model\Model.php(2893): Model->_readDataSource('all', Array)
#6 E:\te\tests\2\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\te\tests\2\app\Controller\UserController.php(55): PaginatorComponent->paginate(NULL)
#8 [internal function]: UserController->view()
#9 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#10 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#12 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-08-21 16:04:05 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Video.active' in 'where clause'
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `User`.`...', false)
#4 E:\te\tests\2\lib\Cake\Model\Model.php(2921): DboSource->read(Object(User), Array)
#5 E:\te\tests\2\lib\Cake\Model\Model.php(2893): Model->_readDataSource('all', Array)
#6 E:\te\tests\2\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\te\tests\2\app\Controller\UserController.php(55): PaginatorComponent->paginate(Array)
#8 [internal function]: UserController->view()
#9 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#10 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#12 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-08-21 16:04:21 Error: [MissingModelException] video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(55): PaginatorComponent->paginate('video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:04:24 Error: [MissingModelException] Video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(55): PaginatorComponent->paginate('Video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:05:16 Error: [MissingModelException] video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(57): PaginatorComponent->paginate('video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:05:17 Error: [MissingModelException] video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(57): PaginatorComponent->paginate('video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:05:48 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Video.active' in 'where clause'
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 E:\te\tests\2\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `User`.`...', false)
#4 E:\te\tests\2\lib\Cake\Model\Model.php(2921): DboSource->read(Object(User), Array)
#5 E:\te\tests\2\lib\Cake\Model\Model.php(2893): Model->_readDataSource('all', Array)
#6 E:\te\tests\2\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\te\tests\2\app\Controller\UserController.php(54): PaginatorComponent->paginate('User')
#8 [internal function]: UserController->view()
#9 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#10 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#12 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-08-21 16:06:00 Error: [MissingModelException] Video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(54): PaginatorComponent->paginate('Video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:06:03 Error: [MissingModelException] Video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(54): PaginatorComponent->paginate('Video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:06:18 Error: [MissingModelException] video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(54): PaginatorComponent->paginate('video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:06:19 Error: [MissingModelException] video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(54): PaginatorComponent->paginate('video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:06:19 Error: [MissingModelException] video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(54): PaginatorComponent->paginate('video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:06:19 Error: [MissingModelException] video
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\app\Controller\UserController.php(54): PaginatorComponent->paginate('video')
#1 [internal function]: UserController->view()
#2 E:\te\tests\2\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#4 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#5 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-08-21 16:08:41 Error: Fatal Error (1): Call to a member function find() on a non-object in [E:\te\tests\2\app\Controller\UserController.php, line 47]
2014-08-21 16:08:41 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 47)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\te\tests\2\a...', 47, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\te\tests\2\a...', 47, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:11:35 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\admin.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\admin.ctp',
)
Request URL: /admin/view
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 16:27:21 Error: [MissingHelperException] Helper class AuthHelper could not be found.
Exception Attributes: array (
  'class' => 'AuthHelper',
  'plugin' => false,
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Auth')
#1 E:\te\tests\2\lib\Cake\View\View.php(837): HelperCollection->__isset('Auth')
#2 E:\te\tests\2\app\View\Video\index.ctp(12): View->__get('Auth')
#3 E:\te\tests\2\lib\Cake\View\View.php(948): include('E:\te\tests\2\a...')
#4 E:\te\tests\2\lib\Cake\View\View.php(910): View->_evaluate('E:\te\tests\2\a...', Array)
#5 E:\te\tests\2\lib\Cake\View\View.php(471): View->_render('E:\te\tests\2\a...')
#6 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#8 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#9 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-08-21 16:30:11 Error: [MissingHelperException] Helper class AuthHelper could not be found.
Exception Attributes: array (
  'class' => 'AuthHelper',
  'plugin' => false,
)
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Auth')
#1 E:\te\tests\2\lib\Cake\View\View.php(837): HelperCollection->__isset('Auth')
#2 E:\te\tests\2\app\View\Video\index.ctp(12): View->__get('Auth')
#3 E:\te\tests\2\lib\Cake\View\View.php(948): include('E:\te\tests\2\a...')
#4 E:\te\tests\2\lib\Cake\View\View.php(910): View->_evaluate('E:\te\tests\2\a...', Array)
#5 E:\te\tests\2\lib\Cake\View\View.php(471): View->_render('E:\te\tests\2\a...')
#6 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#8 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#9 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-08-21 16:33:47 Error: [MissingViewException] View file "E:\te\tests\2\app\View\video\apply.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\te\\tests\\2\\app\\View\\video\\apply.ctp',
)
Request URL: /admin/apply/4
Stack Trace:
#0 E:\te\tests\2\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\te\tests\2\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 E:\te\tests\2\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(IndexController), Object(CakeRequest))
#4 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-21 16:51:06 Error: Fatal Error (1): Call to undefined method PaginatorComponent::options() in [E:\te\tests\2\app\Controller\IndexController.php, line 22]
2014-08-21 16:51:06 Error: [FatalErrorException] Call to undefined method PaginatorComponent::options()
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:51:36 Error: Fatal Error (1): Call to undefined method PaginatorComponent::settings() in [E:\te\tests\2\app\Controller\IndexController.php, line 22]
2014-08-21 16:51:36 Error: [FatalErrorException] Call to undefined method PaginatorComponent::settings()
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:51:37 Error: Fatal Error (1): Call to undefined method PaginatorComponent::settings() in [E:\te\tests\2\app\Controller\IndexController.php, line 22]
2014-08-21 16:51:37 Error: [FatalErrorException] Call to undefined method PaginatorComponent::settings()
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:51:37 Error: Fatal Error (1): Call to undefined method PaginatorComponent::settings() in [E:\te\tests\2\app\Controller\IndexController.php, line 22]
2014-08-21 16:51:37 Error: [FatalErrorException] Call to undefined method PaginatorComponent::settings()
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:51:37 Error: Fatal Error (1): Call to undefined method PaginatorComponent::settings() in [E:\te\tests\2\app\Controller\IndexController.php, line 22]
2014-08-21 16:51:37 Error: [FatalErrorException] Call to undefined method PaginatorComponent::settings()
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:51:37 Error: Fatal Error (1): Call to undefined method PaginatorComponent::settings() in [E:\te\tests\2\app\Controller\IndexController.php, line 22]
2014-08-21 16:51:37 Error: [FatalErrorException] Call to undefined method PaginatorComponent::settings()
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:51:38 Error: Fatal Error (1): Call to undefined method PaginatorComponent::settings() in [E:\te\tests\2\app\Controller\IndexController.php, line 22]
2014-08-21 16:51:38 Error: [FatalErrorException] Call to undefined method PaginatorComponent::settings()
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\te\tests\2\a...', 22, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 16:56:47 Error: Fatal Error (4): syntax error, unexpected ')' in [E:\te\tests\2\app\Config\routes.php, line 30]
2014-08-21 16:56:47 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /
Stack Trace:
#0 E:\te\tests\2\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\te\tests\2\a...', 30)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\te\tests\2\a...', 30, Array)
#2 E:\te\tests\2\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\te\tests\2\a...', 30, Array)
#3 E:\te\tests\2\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 17:08:19 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/video.id/desc
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:08:50 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/video.id/desc
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:09:31 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/video.id/desc
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:15:58 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/3/video.id/desc
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:17:03 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/video.id/desc
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:21:17 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/video.id/desc
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:21:45 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/2/video.id/desc
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:21:48 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/2/video.id/desc
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:23:10 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/2
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 17:23:18 Error: [MissingControllerException] Controller class PageController could not be found.
Exception Attributes: array (
  'class' => 'PageController',
  'plugin' => NULL,
)
Request URL: /page/2
Stack Trace:
#0 E:\te\tests\2\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-21 19:39:16 Error: Fatal Error (4): syntax error, unexpected '[' in [Z:\home\test\www\app\Controller\IndexController.php, line 5]
2014-08-21 19:39:16 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /
Stack Trace:
#0 Z:\home\test\www\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'Z:\home\test\ww...', 5)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'Z:\home\test\ww...', 5, Array)
#2 Z:\home\test\www\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'Z:\home\test\ww...', 5, Array)
#3 Z:\home\test\www\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-21 14:42:07 Error: [MissingViewException] View file "Z:\home\test\www\app\View\User\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'Z:\\home\\test\\www\\app\\View\\User\\login.ctp',
)
Request URL: /admin/auth
Stack Trace:
#0 Z:\home\test\www\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 Z:\home\test\www\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 Z:\home\test\www\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 Z:\home\test\www\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UserController), Object(CakeRequest))
#4 Z:\home\test\www\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
